Header stock
Bobjka/2075847-gllacy-34 pull request #1
Opened 2022-09-07 14:34 UTC by Bobjka

2022-09-11 00:44 UTC, Espanol-nikkol requested changes

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +          <a class="navigation-user-link enter-link" href="#">Вход
давай кнопкой сделаем, мы ведь знаем, что она никуда не будет вести, а только открывать поповер

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +          <a class="navigation-user-link basket-link" href="#">2 товара
аналогично входу

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +          <a class="navigation-user-link search-link" href="#">
тоже не ссылка

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +              <input class="field" required placeholder="Поиск по сайту" type="text" name="navigation-form" id="navigation-form">
стоит использовать type `search`. Этот момент наверняка учитывается поисковиками, плюс есть особенности отображения подобных полей, например, на телефонах

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +                <button class="button-enter button" type="button">Войти</button>
submit должен быть
Даже если мы перед входом обрабатываем данные в JS, проще подписаться на submit (там можно взять данные формы), чем просто на click

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +              <button class="button-total button" type="button">Оформить заказ</button>
а вот это скорее всего ссылка. На страницу оформления заказа

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +          <a class="main-button promotions-raspberry-button" href="">Хочу подарок</a>
\# забыл в href

2022-09-11 00:44 UTC, Espanol-nikkol commented on index.html
> +          <a class="main-button promotions-raspberry-button" href="">Хочу подарок</a>
и здесь #

2022-09-12 10:41 UTC, Bobjka commented on index.html
> +              <input class="field" required placeholder="Поиск по сайту" type="text" name="navigation-form" id="navigation-form">
type search добавляет кнопку "х" (удалить текст), я так понял она не стилизуется? Я ее просто спрятал и оставил свою кнопку которая никак не привязана к удалению текста.

2022-09-27 08:18 UTC, merged